[pages]
# functions 디렉터리의 위치를 지정합니다.
# 기본값은 "functions"이므로 생략 가능
# [pages.functions]
# dir = "functions"

# nodejs 호환성 모드를 활성화합니다.
[pages.functions.build]
nodejs_compat = true

[pages]
compatibility_flags = ["nodejs_compat"]